- .github/workflows/packAndImage.yml
- .goreleaser.yaml
- build/resources/join.sh
- build/resources/leave.sh
- build/resources/start.sh
> fix git action

- .goreleaser.yaml
> fix .goreleaser.yaml

- build/resources/Dockerfile
- build/resources/config.yml.tmp
> change default port

- build/resources/Dockerfile
> APP=apinto

- build/resources/Dockerfile
> alter centos version to 7.9.2009

- .github/workflows/actions.yaml
- .goreleaser.yaml
Description
1. Create a github actions automatic packaging release script that supports Linux, Darwin systems, amd64, arm, and i386 architectures
Checklist
> 新建github-actions自动打包发版脚本

- .github/workflows/actions.yaml
- .goreleaser.yaml
- go.mod
> 修改github-actions打包脚本

- build/resources/Dockerfile
- build/resources/apinto.yml.tpl
- build/resources/config.yml.tmp
- build/resources/config.yml.tpl
- build/resources/install.sh
> update resources files

- drivers/plugins/cors/cors.go
> fix cors.DoHttpFilter "option" -> http.MethodOptions

- drivers/service/factory.go
- upstream/ip-hash/ip_hash.go
> 增加ip hash负载均衡算法

- upstream/ip-hash/ip_hash.go
> ip-hash负载均衡算法增加node数量判断

- build/resources/install.sh
> update install.sh: add install,upgrade

- drivers/plugins/grpc-proxy-rewrite/config.go
- drivers/plugins/grpc-proxy-rewrite/driver.go
- drivers/plugins/grpc-proxy-rewrite/proxy-rewrite.go
- drivers/router/dubbo2-router/handler.go
- drivers/router/grpc-router/manager/complete.go
- go.mod
- node/grpc-context/context.go
> 修改grpc重写插件，tls相关配置删除

- drivers/service/config.go
> 负载算法新增ip-hash选项

- .goreleaser.yaml
> 修改goreleaser脚本

- drivers/output/kafka/config.go
- go.mod
> 修改kafka version字段

- app/apinto/profession.go
- app/apinto/worker.go
- drivers/discovery/consul/clients.go
- drivers/discovery/polaris/clients.go
- drivers/discovery/polaris/config.go
- drivers/discovery/polaris/driver.go
- drivers/discovery/polaris/factory.go
- drivers/discovery/polaris/polaris.go
- drivers/discovery/polaris/polaris_test.go
- go.mod
北极星是腾讯开源的服务治理平台，apinto服务发现模块接入北极星作为服务发现，代码已在本地测试。如果可以合并，我在完善文档apinto-docs，控制台项目apinto-dashboard新建服务发现给出北极星选项。
- 北极星文档：https://polarismesh.cn/docs/%E5%8C%97%E6%9E%81%E6%98%9F%E6%98%AF%E4%BB%80%E4%B9%88/%E7%AE%80%E4%BB%8B/
> feat：服务发现接入北极星

- drivers/app/manager/manager.go
> chore: slice append replace loop

- app/apinto/plugin.go
- drivers/output/fileoutput/config.go
- drivers/output/fileoutput/write.go
- drivers/output/httpoutput/config.go
- drivers/output/httpoutput/http.go
- drivers/output/kafka/config.go
- drivers/output/kafka/factory.go
- drivers/output/kafka/output.go
- drivers/output/kafka/producer.go
- drivers/output/nsq/config.go
- drivers/output/nsq/write.go
- drivers/output/syslog/config.go
- drivers/output/syslog/linux.go
- drivers/plugins/request-file-parse/executor.go
- go.mod
- node/http-context/header.go
> 日志输出器新增内容截断配置

- node/http-context/clone.go
- node/http-context/context.go
> 修复目标IP、目标端口获取失败的问题

- drivers/plugins/gRPC-to-http/complete.go
- node/fasthttp-client/client.go
- node/fasthttp-client/client_test.go
- node/fasthttp-client/dial.go
- node/http-context/clone.go
- node/http-context/context.go
2、获取后端服务IP、端口号方法修改
Description
Checklist
> 1、后端服务响应自动重定向完成

- build/resources/join.sh
> 修改单节点连接api失败后以状态码0退出脚本，不进行重启操作

- drivers/ai-provider/openAI/openai_test.go
> update openai test

- drivers/ai-provider/openAI/openai_test.go
> add: validNormalFunc

- drivers/.gitignore
- drivers/ai-provider/moonshot/message.go
- drivers/ai-provider/moonshot/mode.go
- drivers/ai-provider/moonshot/moonshot_test.go
> add: enhance Moonshot API response handling and testing

- .gitignore
- drivers/ai-provider/groq/message.go
- drivers/ai-provider/groq/mode.go
- drivers/ai-provider/groq/mode_test.go
- drivers/ai-provider/minimax/message.go
- drivers/ai-provider/minimax/mode.go
- drivers/ai-provider/minimax/mode_test.go
- drivers/ai-provider/stepfun/message.go
- drivers/ai-provider/stepfun/mode.go
- drivers/ai-provider/stepfun/mode_test.go
> 补充记录ai供应商 阶跃星辰 token使用情况

- ai-convert/mapping.go
- ai-convert/message.go
- ai-convert/openai.go
- drivers/ai-key/executor.go
- drivers/ai-provider/executor.go
- drivers/ai-provider/mapping.go
- drivers/plugins/access-relational/handler.go
- drivers/plugins/ai-formatter/executor.go
- drivers/plugins/ai-prompt/executor.go
- drivers/plugins/ai-prompt/factory.go
- encoder/gzip.go
> update mapping rule

- drivers/ai-provider/customize-openai/customize-openai.go
> 修复自定义openai驱动没有读取apikey的问题

- ai-convert/mapping.go
> fix: model config is nil

- drivers/ai-provider/bailianyun/bailianyun.go
- drivers/ai-provider/hugging-face/hugging_face.go
- drivers/ai-provider/xinference/xinference.go
- drivers/ai-provider/zhipuai/zhipu.go
> 修复部分ai供应商id对齐问题

- drivers/ai-provider/vertex_ai/vertex_ai.go
> 完善vertex ai 错误回调

- drivers/plugins/ai-prompt/executor.go
> 修复缺少prompt信息的问题
